### ISSUE TITLE
Support for variable array length

### ISSUE THREAD

**Issue by jimmiebtlr** [rafaqz/Flatten.jl#15]
Wondering what adding support for array length only based on passed in object would look like.  My understanding is this isn't currently supported.

Thinking flatten could also return a function or another object to be used when reconstructing.

Thoughts on the best way to approach this?

**Comment by rafaqz** [comment]
Do you mean tuple length?

`length(flatten(obj))`

**Comment by rafaqz** [comment]
Or do you mean flattening Arrays? That's not easy as this is all compile-time generated code. You can swap in StaticArrays and everything works, because the length is known at compile time.

**Comment by rafaqz** [comment]
Otherwise you could write something using FieldMetadata.jl field like `@meta length` and a method on `flatten` and `reconstruct` for `Array` that used the metadata for the array fields to update the `n` counter. That would be fine for flattening Array.

Flatten.jl is written so that everything is extensible and you can do things like this. But working with nested generated functions is insane in practice so maybe not so easy.

**Comment by jimmiebtlr** [comment]
Meaning along the lines of 

```
struct Something
  someField::Vector{Float32}
end
```

**Comment by rafaqz** [comment]
Just use StaticArrays instead of Vector

**Comment by jimmiebtlr** [comment]
Will give that a try, ty.
