### ISSUE TITLE
Flatten.action not defined

### ISSUE THREAD

**Issue by baggepinnen** [rafaqz/Flatten.jl#5]
The readme talks about
`Flatten.action(::DataFrame) = Flatten.Ignore()`
but there is no such function `action`

**Comment by rafaqz** [comment]
There is on master:

https://github.com/rafaqz/Flatten.jl/blob/master/src/Flatten.jl#L21

However, this is all going to change in a few weeks as I have a better method of generalising the package,. I just can't implement it yet due to other work requirements, and don't want to release the current API as it will change. So please bear with me until mid June, the new version will be much more powerful and general.
